In [1]:
import pandas as pd

In [5]:
datos = pd.read_csv('Catálogo_Nacional_de_Estaciones_del_IDEAM_20260620.csv')
datos_Bogota = datos[datos['Departamento'].str.contains('Bogotá', case=False)]
datos_Bogota

,Codigo,Nombre,Categoria,Tecnologia,Estado,Departamento,Municipio,Ubicación,Altitud,LONGITUD,LATITUD,Fecha_instalacion,Fecha_suspension,Area Operativa,Corriente,Area Hidrografica,Zona Hidrografica,Subzona hidrografica,Entidad
15,21205380,HIPOTECHO [21205380],Climatológica Ordinaria,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.13333333, 4.633333333)","2,550",-74.133333,4.633333,15/05/1957,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...
42,2120000122,COLEGIO INEM FRANCISCO DE PAULA SANTANDER (IED...,Pluviométrica,Automática con Telemetría,Activa,Bogotá,"Bogotá, D.C","(-74.154993, 4.624567)","2,557",-74.154993,4.624567,01/11/2016,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DISTRITAL DE GESTIÓN DE RIESGOS Y CA...
45,21200310,CERRO DE SUBA [21200310],Pluviométrica,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.06666667, 4.75)","2,691",-74.066667,4.750000,15/09/1947,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...
47,21206500,COLEGIO ABRAHAM LINCOLN [21206500],Climatológica Ordinaria,Convencional,Suspendida,Bogotá,"Bogotá, D.C","(-74.06158333, 4.756638889)","2,570",-74.061583,4.756639,15/10/1994,03/11/2009,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
49,2120000169,COLEGIO LA BELLEZA (IED) [2120000169],Pluviométrica,Automática con Telemetría,Activa,Bogotá,"Bogotá, D.C","(-74.09244, 4.53059)","2,949",-74.092440,4.530590,01/09/2019,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DISTRITAL DE GESTIÓN DE RIESGOS Y CA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9303,21206730,GIBRALTAR [21206730],Climatológica Principal,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.18333333, 4.65)","2,581",-74.183333,4.650000,15/02/2004,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,ESTACIONES PARTICULARES
9430,21207030,DECANTADORES [21207030],Limnimétrica,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.06666667, 4.566666667)","2,885",-74.066667,4.566667,15/01/1927,NaN,Area Operativa 11 - Cundinamarca-Amazonas,SAN FRANCISCO,Magdalena Cauca,Alto Magdalena,Río Bogotá,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...
9446,21201200,ESCUELA LA UNION [21201200],Pluviométrica,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.18381, 4.34264)","3,378",-74.183810,4.342640,01/08/2007,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
9454,21205012,UNIVERSIDAD NACIONAL [21205012],Climatológica Principal,Automática con Telemetría,Activa,Bogotá,"Bogotá, D.C","(-74.08892, 4.63723)","2,556",-74.088920,4.637230,19/08/2004,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
9474,21206690,COLEGIO MIGUEL A. CARO [21206690],Climatológica Ordinaria,Convencional,Activa,Bogotá,"Bogotá, D.C","(-74.03111111, 4.813166667)","2,700",-74.031111,4.813167,15/11/2001,NaN,Area Operativa 11 - Cundinamarca-Amazonas,NaN,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...

In [6]:
precipitacion = pd.read_csv('descargaDhime.csv')
precipitacion

,CodigoEstacion,NombreEstacion,Variable,Parametro,Fecha,Unidad,Valor,NivelAprobacion
0,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-12 00:00,mm,0.0,Preliminar
1,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-13 00:00,mm,0.0,Preliminar
2,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-14 00:00,mm,1.9,Preliminar
3,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-15 00:00,mm,1.9,Preliminar
4,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-16 00:00,mm,0.3,Preliminar
5,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-17 00:00,mm,0.9,Preliminar
6,21202280,SEDE IDEAM CALLE 25D KRA [21202280],PRECIPITACION,Día pluviométrico (convencional),2026-06-18 00:00,mm,3.1,Preliminar